#!/bin/bash
#
# Add all new Bastion modules to Xcode project
# Auto-generated by Claude
# Date: 2026-01-20
#

set -e

echo "🔧 Adding new modules to Bastion.xcodeproj..."
echo ""

cd /Volumes/Data/xcode/Bastion

# New modules to add
NEW_MODULES=(
    "Bastion/Security/ExploitModules/SMBModule.swift"
    "Bastion/Security/ExploitModules/DNSModule.swift"
    "Bastion/Security/ExploitModules/LDAPModule.swift"
    "Bastion/Security/LateralMovementMapper.swift"
    "Bastion/Security/VulnerabilityChainer.swift"
    "Bastion/Security/MITREATTACKMapper.swift"
    "Bastion/Security/RemediationScriptGenerator.swift"
    "Bastion/Security/ContinuousMonitor.swift"
    "Bastion/Security/AnomalyDetector.swift"
    "Bastion/Security/TimelineReconstructor.swift"
)

echo "Files to add:"
for file in "${NEW_MODULES[@]}"; do
    if [ -f "$file" ]; then
        echo "  ✓ $file"
    else
        echo "  ❌ $file (NOT FOUND)"
    fi
done

echo ""
echo "Opening Xcode..."
open Bastion.xcodeproj

echo ""
echo "=========================================="
echo "MANUAL STEPS REQUIRED:"
echo "=========================================="
echo ""
echo "In Xcode:"
echo "1. Wait for Xcode to fully load"
echo "2. In Project Navigator, right-click 'Security' folder"
echo "3. Select 'Add Files to \"Bastion\"...'"
echo "4. Navigate to: /Volumes/Data/xcode/Bastion/Bastion/Security/"
echo "5. Select these files:"
echo "   - LateralMovementMapper.swift"
echo "   - VulnerabilityChainer.swift"
echo "   - MITREATTACKMapper.swift"
echo "   - RemediationScriptGenerator.swift"
echo "   - ContinuousMonitor.swift"
echo "   - AnomalyDetector.swift"
echo "   - TimelineReconstructor.swift"
echo "6. Click 'Add'"
echo ""
echo "7. Right-click 'Security/ExploitModules' folder"
echo "8. Select 'Add Files to \"Bastion\"...'"
echo "9. Select these files:"
echo "   - SMBModule.swift"
echo "   - DNSModule.swift"
echo "   - LDAPModule.swift"
echo "10. Click 'Add'"
echo ""
echo "11. Press ⌘B to build"
echo ""
echo "=========================================="
echo "DEPENDENCIES TO INSTALL:"
echo "=========================================="
echo ""
echo "brew install sshpass     # For SSH password testing"
echo "brew install nmap        # For SMB/advanced scanning"
echo "brew install enum4linux  # For SMB enumeration (optional)"
echo ""
echo "=========================================="

echo ""
echo "✅ Xcode opened. Follow the manual steps above to add files."
