//
//  PDFGenerator.swift
//  Bastion
//
//  Enterprise PDF report generation with AI analysis
//  Author: Jordan Koch
//  Date: 2025-01-17
//

import Foundation
import PDFKit
import AppKit

@MainActor
class PDFGenerator {
    static let shared = PDFGenerator()

    private init() {}

    // Generate comprehensive PDF report
    func generateReport(results: ScanResults, aiSummary: String) async throws -> URL {
        let pdfData = NSMutableData()
        let consumer = CGDataConsumer(data: pdfData as CFMutableData)!
        var mediaBox = CGRect(x: 0, y: 0, width: 612, height: 792) // US Letter

        guard let pdf = CGContext(consumer: consumer, mediaBox: &mediaBox, nil) else {
            throw PDFError.creationFailed
        }

        // Title Page
        pdf.beginPage(mediaBox: &mediaBox)
        drawTitlePage(context: pdf, results: results)
        pdf.endPage()

        // Executive Summary
        pdf.beginPage(mediaBox: &mediaBox)
        drawExecutiveSummary(context: pdf, results: results, aiSummary: aiSummary)
        pdf.endPage()

        // Network Overview
        pdf.beginPage(mediaBox: &mediaBox)
        drawNetworkOverview(context: pdf, results: results)
        pdf.endPage()

        // Vulnerability Details (one page per device)
        for device in results.devices where !device.vulnerabilities.isEmpty {
            pdf.beginPage(mediaBox: &mediaBox)
            drawDeviceDetails(context: pdf, device: device)
            pdf.endPage()
        }

        // Remediation Plan
        pdf.beginPage(mediaBox: &mediaBox)
        drawRemediationPlan(context: pdf, results: results)
        pdf.endPage()

        pdf.closePDF()

        // Save to file
        let filename = "Bastion_Report_\(Date().formatted(date: .numeric, time: .omitted).replacingOccurrences(of: "/", with: "-")).pdf"
        let documentsPath = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        let pdfPath = documentsPath.appendingPathComponent(filename)

        try pdfData.write(to: pdfPath)

        return pdfPath
    }

    // Draw title page
    private func drawTitlePage(context: CGContext, results: ScanResults) {
        let width = context.boundingBoxOfClipPath.width
        let height = context.boundingBoxOfClipPath.height

        // Logo/Title
        drawText(context: context, text: "BASTION", font: .boldSystemFont(ofSize: 48),
                 x: width / 2, y: height - 200, alignment: .center, color: .black)

        drawText(context: context, text: "Security Assessment Report", font: .systemFont(ofSize: 24),
                 x: width / 2, y: height - 250, alignment: .center, color: .darkGray)

        // Report Info
        let dateStr = results.scanDate.formatted(date: .long, time: .standard)
        drawText(context: context, text: "Report Date: \(dateStr)", font: .systemFont(ofSize: 14),
                 x: width / 2, y: height / 2, alignment: .center, color: .black)

        drawText(context: context, text: "Network: \(results.networkCIDR)", font: .systemFont(ofSize: 14),
                 x: width / 2, y: height / 2 - 30, alignment: .center, color: .black)

        drawText(context: context, text: "Devices Scanned: \(results.devices.count)", font: .systemFont(ofSize: 14),
                 x: width / 2, y: height / 2 - 60, alignment: .center, color: .black)

        // Severity Badge
        let severityText: String
        let severityColor: NSColor

        if results.criticalCount > 0 {
            severityText = "CRITICAL"
            severityColor = .red
        } else if results.highCount > 0 {
            severityText = "HIGH RISK"
            severityColor = .orange
        } else if results.mediumCount > 0 {
            severityText = "MEDIUM RISK"
            severityColor = .yellow
        } else {
            severityText = "LOW RISK"
            severityColor = .green
        }

        context.setFillColor(severityColor.cgColor)
        context.fill(CGRect(x: width / 2 - 100, y: 200, width: 200, height: 60))

        drawText(context: context, text: severityText, font: .boldSystemFont(ofSize: 20),
                 x: width / 2, y: 220, alignment: .center, color: .white)

        // Footer
        drawText(context: context, text: "Generated by Bastion - AI-Powered Penetration Testing",
                 font: .systemFont(ofSize: 10),
                 x: width / 2, y: 30, alignment: .center, color: .gray)
    }

    // Draw executive summary
    private func drawExecutiveSummary(context: CGContext, results: ScanResults, aiSummary: String) {
        var yPos: CGFloat = context.boundingBoxOfClipPath.height - 50

        drawText(context: context, text: "Executive Summary", font: .boldSystemFont(ofSize: 24),
                 x: 50, y: yPos, alignment: .left, color: .black)
        yPos -= 40

        // AI Summary
        drawText(context: context, text: "AI Analysis:", font: .boldSystemFont(ofSize: 16),
                 x: 50, y: yPos, alignment: .left, color: .black)
        yPos -= 25

        let summaryLines = wrapText(aiSummary, maxWidth: 500, font: .systemFont(ofSize: 12))
        for line in summaryLines.prefix(15) {
            drawText(context: context, text: line, font: .systemFont(ofSize: 12),
                     x: 50, y: yPos, alignment: .left, color: .darkGray)
            yPos -= 15
        }

        yPos -= 20

        // Vulnerability Summary
        drawText(context: context, text: "Vulnerability Summary:", font: .boldSystemFont(ofSize: 16),
                 x: 50, y: yPos, alignment: .left, color: .black)
        yPos -= 25

        drawText(context: context, text: "Critical: \(results.criticalCount)", font: .systemFont(ofSize: 14),
                 x: 70, y: yPos, alignment: .left, color: .red)
        yPos -= 20

        drawText(context: context, text: "High: \(results.highCount)", font: .systemFont(ofSize: 14),
                 x: 70, y: yPos, alignment: .left, color: .orange)
        yPos -= 20

        drawText(context: context, text: "Medium: \(results.mediumCount)", font: .systemFont(ofSize: 14),
                 x: 70, y: yPos, alignment: .left, color: NSColor(red: 0.8, green: 0.6, blue: 0, alpha: 1))
        yPos -= 20

        drawText(context: context, text: "Low: \(results.lowCount)", font: .systemFont(ofSize: 14),
                 x: 70, y: yPos, alignment: .left, color: .blue)
    }

    // Draw network overview
    private func drawNetworkOverview(context: CGContext, results: ScanResults) {
        var yPos: CGFloat = context.boundingBoxOfClipPath.height - 50

        drawText(context: context, text: "Network Overview", font: .boldSystemFont(ofSize: 24),
                 x: 50, y: yPos, alignment: .left, color: .black)
        yPos -= 40

        drawText(context: context, text: "Discovered Devices:", font: .boldSystemFont(ofSize: 16),
                 x: 50, y: yPos, alignment: .left, color: .black)
        yPos -= 25

        // Device table header
        drawText(context: context, text: "IP Address", font: .boldSystemFont(ofSize: 12),
                 x: 50, y: yPos, alignment: .left, color: .black)
        drawText(context: context, text: "Hostname", font: .boldSystemFont(ofSize: 12),
                 x: 180, y: yPos, alignment: .left, color: .black)
        drawText(context: context, text: "Type", font: .boldSystemFont(ofSize: 12),
                 x: 320, y: yPos, alignment: .left, color: .black)
        drawText(context: context, text: "Vulns", font: .boldSystemFont(ofSize: 12),
                 x: 450, y: yPos, alignment: .left, color: .black)
        drawText(context: context, text: "Score", font: .boldSystemFont(ofSize: 12),
                 x: 520, y: yPos, alignment: .left, color: .black)
        yPos -= 20

        // Device rows
        for device in results.devices.prefix(25) {
            let vulnCount = device.vulnerabilities.count
            let scoreColor = device.securityScore > 70 ? NSColor.green :
                           device.securityScore > 40 ? NSColor.orange : NSColor.red

            drawText(context: context, text: device.ipAddress, font: .systemFont(ofSize: 10),
                     x: 50, y: yPos, alignment: .left, color: .black)
            drawText(context: context, text: device.hostname ?? "-", font: .systemFont(ofSize: 10),
                     x: 180, y: yPos, alignment: .left, color: .darkGray)
            drawText(context: context, text: device.deviceType.rawValue, font: .systemFont(ofSize: 10),
                     x: 320, y: yPos, alignment: .left, color: .darkGray)
            drawText(context: context, text: "\(vulnCount)", font: .systemFont(ofSize: 10),
                     x: 450, y: yPos, alignment: .left, color: vulnCount > 0 ? .red : .green)
            drawText(context: context, text: "\(device.securityScore)", font: .systemFont(ofSize: 10),
                     x: 520, y: yPos, alignment: .left, color: scoreColor)

            yPos -= 15
        }
    }

    // Draw device details
    private func drawDeviceDetails(context: CGContext, device: Device) {
        var yPos: CGFloat = context.boundingBoxOfClipPath.height - 50

        drawText(context: context, text: "Device: \(device.displayName)", font: .boldSystemFont(ofSize: 20),
                 x: 50, y: yPos, alignment: .left, color: .black)
        yPos -= 30

        drawText(context: context, text: "IP: \(device.ipAddress)   Security Score: \(device.securityScore)/100",
                 font: .systemFont(ofSize: 12),
                 x: 50, y: yPos, alignment: .left, color: .darkGray)
        yPos -= 30

        drawText(context: context, text: "Vulnerabilities Found:", font: .boldSystemFont(ofSize: 16),
                 x: 50, y: yPos, alignment: .left, color: .black)
        yPos -= 25

        for vuln in device.vulnerabilities.prefix(15) {
            let severityColor: NSColor = {
                switch vuln.severity {
                case .critical: return .red
                case .high: return .orange
                case .medium: return NSColor(red: 0.8, green: 0.6, blue: 0, alpha: 1)
                case .low: return .blue
                case .informational: return .gray
                }
            }()

            drawText(context: context, text: "[\(vuln.severity.rawValue)] \(vuln.title)",
                     font: .boldSystemFont(ofSize: 12),
                     x: 70, y: yPos, alignment: .left, color: severityColor)
            yPos -= 15

            let descLines = wrapText(vuln.description, maxWidth: 450, font: .systemFont(ofSize: 10))
            for line in descLines.prefix(3) {
                drawText(context: context, text: line, font: .systemFont(ofSize: 10),
                         x: 90, y: yPos, alignment: .left, color: .darkGray)
                yPos -= 12
            }
            yPos -= 5
        }
    }

    // Draw remediation plan
    private func drawRemediationPlan(context: CGContext, results: ScanResults) {
        var yPos: CGFloat = context.boundingBoxOfClipPath.height - 50

        drawText(context: context, text: "Remediation Plan", font: .boldSystemFont(ofSize: 24),
                 x: 50, y: yPos, alignment: .left, color: .black)
        yPos -= 40

        drawText(context: context, text: "Immediate Actions Required:", font: .boldSystemFont(ofSize: 16),
                 x: 50, y: yPos, alignment: .left, color: .black)
        yPos -= 25

        var actionNumber = 1
        for device in results.devices where device.criticalVulnCount > 0 || device.highVulnCount > 0 {
            drawText(context: context, text: "\(actionNumber). \(device.displayName) (\(device.ipAddress))",
                     font: .boldSystemFont(ofSize: 12),
                     x: 70, y: yPos, alignment: .left, color: .black)
            yPos -= 15

            if device.criticalVulnCount > 0 {
                drawText(context: context, text: "• Patch \(device.criticalVulnCount) critical vulnerabilities",
                         font: .systemFont(ofSize: 11),
                         x: 90, y: yPos, alignment: .left, color: .red)
                yPos -= 15
            }

            if device.services.contains(where: { $0.name == "SSH" }) {
                drawText(context: context, text: "• Change default SSH credentials",
                         font: .systemFont(ofSize: 11),
                         x: 90, y: yPos, alignment: .left, color: .darkGray)
                yPos -= 15
            }

            yPos -= 10
            actionNumber += 1

            if actionNumber > 10 { break }
        }
    }

    // Helper: Draw text
    private func drawText(context: CGContext, text: String, font: NSFont, x: CGFloat, y: CGFloat,
                         alignment: NSTextAlignment, color: NSColor) {
        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: color
        ]

        let attributedString = NSAttributedString(string: text, attributes: attributes)
        let line = CTLineCreateWithAttributedString(attributedString)

        var xPos = x
        if alignment == .center {
            let bounds = CTLineGetBoundsWithOptions(line, [])
            xPos = x - bounds.width / 2
        } else if alignment == .right {
            let bounds = CTLineGetBoundsWithOptions(line, [])
            xPos = x - bounds.width
        }

        context.textPosition = CGPoint(x: xPos, y: y)
        CTLineDraw(line, context)
    }

    // Helper: Wrap text
    private func wrapText(_ text: String, maxWidth: CGFloat, font: NSFont) -> [String] {
        var lines: [String] = []
        let words = text.components(separatedBy: " ")
        var currentLine = ""

        for word in words {
            let testLine = currentLine.isEmpty ? word : currentLine + " " + word
            let size = (testLine as NSString).size(withAttributes: [.font: font])

            if size.width > maxWidth && !currentLine.isEmpty {
                lines.append(currentLine)
                currentLine = word
            } else {
                currentLine = testLine
            }
        }

        if !currentLine.isEmpty {
            lines.append(currentLine)
        }

        return lines
    }
}

enum PDFError: LocalizedError {
    case creationFailed

    var errorDescription: String? {
        "Failed to create PDF document"
    }
}
